/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;
public class GoogleBillboard{
    public boolean isPrime(long n) {
        if (n <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
    public long firstPrimeNumberIn(String n) {
        for (int i = 0; i < n.length(); i++) {
            int num = 0;
            for (int j = i; j < n.length(); j++) {
                String d = n.substring(j, j + 1);
                if (d.equals("0")){
                    num = num * 10;
                }
                else if (d.equals("1")){
                    num = num * 10 + 1;
                }
                else if (d.equals("2")){
                    num = num * 10 + 2;
                }
                else if (d.equals("3")){
                    num = num * 10 + 3;
                }
                else if (d.equals("4")){
                    num = num * 10 + 4;
                }
                else if (d.equals("5")){
                    num = num * 10 + 5;
                }
                else if (d.equals("6")){
                    num = num * 10 + 6;
                }
                else if (d.equals("7")){
                    num = num * 10 + 7;
                }
                else if (d.equals("8")){
                    num = num * 10 + 8;
                }
                else{
                    num = num * 10 + 9;
                }
                if (isPrime(num)) {
                    return num;
                }
            }
        }
        return -1;
    }
}
